name: Docker Build & Publish

on:
  push:
    tags: [ "v*.*.*" ]

env:
  REGISTRY: docker.io
  DOCKER_REPO: alex78218/wt-dev-blog

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 步骤1：检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤2：设置 QEMU（跨平台构建必需）
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 步骤3：设置 Buildx（多平台构建必需）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          platforms: linux/amd64,linux/arm64,linux/arm/v7,windows/amd64

      # 步骤4：提取版本元数据
      - name: Extract version metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REPO }}
          tags: |
            type=raw,value=latest
            type=ref,event=tag

      # 步骤5：登录 Docker 仓库
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 步骤6：多平台构建并推送
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: |
            linux/amd64
            linux/arm64
          # Windows 专用配置
          build-args: |
            WINDOWS_VERSION=1809
          # 构建缓存配置
          cache-from: type=gha
          cache-to: type=gha,mode=max